name: Texter

on: push

jobs:
  publish_article:
    name: Textando

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          persist-credentials: false

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache de pacotes Python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Executar script Python
        run: |
          python legenda_teste.py

      - name: Configurar Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Adicionar e commitar mudanças
        run: |
          git add legenda.txt
          git commit -m "Atualizar arquivo de legenda [skip ci]" || echo "No changes to commit"

      - name: Push mudanças
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/espiritualidadenapraticaclinica/espiritualidadenapraticaclinica.github.io.git
          git push origin main
