name: Pubmed

on:
  push
  workflow_dispatch

jobs:
  publish_article:
    name: Publicar Artigo no Site

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Manter o fluxo de trabalho ativo
        uses: entepotenz/keep-github-actions-alive-min-dependencies@v1

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache de pacotes Python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Python para encontrar artigo e postar no site
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python pubmed.py

      - name: Commit e push das mudanças no index.html
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git add conteudo/index.html
          git add legenda.txt
          git commit -m "Atualizar index.html e arquivo de legenda com novo artigo [skip ci]"  # Ignorar a execução do workflow para este commit
          git push
