name: Pubmed

on: push

 #  schedule:

   #     - cron: '0 10 * * *'
jobs:
  publish_article:
    name: Publicar Artigo no Site

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          persist-credentials: false

      - name: Manter o fluxo de trabalho ativo
        uses: entepotenz/keep-github-actions-alive-min-dependencies@v1

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache de pacotes Python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Python para encontrar artigo e postar no site
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          python pubmed.py

      - name: Configurar Git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

      - name: Atualizar repositório local com remoto
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/espiritualidadenapraticaclinica/espiritualidadenapraticaclinica.github.io.git
          git fetch origin
          git pull origin main --rebase

      - name: Adicionar e commitar mudanças
        run: |
          git add legenda.txt
          git add conteudo/index.html
          git commit -m "Atualizar arquivo de legenda e index [skip ci]" || echo "No changes to commit"

      - name: Push mudanças
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git push origin main
