name: Pubmed

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  publish_article:
    name: Publicar Artigo no Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          persist-credentials: false

      - name: Configurar o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache de pacotes Python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script Python
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          python pubmed.py
        continue-on-error: true

      - name: Verificar mudanças
        id: changes
        run: |
          git add legenda.txt conteudo/index.html
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commitar e push (se houver mudanças)
        if: steps.changes.outputs.changes != '0'
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Atualizar conteúdo [skip ci]"
          git push origin main
